-- Create types for Enums OPTIONAL NOT IMPLEMENTED HERE
-- CREATE TYPE suggestion_status_enum AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');
-- CREATE TYPE trigger_reason_enum AS ENUM ('AGENT_OFFLINE', 'INITIAL', 'MANUAL');
-- CREATE TYPE agent_status_enum AS ENUM ('AVAILABLE', 'BUSY', 'OFFLINE');


-- Agents Table
CREATE TABLE agents (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR,
    active_order_count INTEGER DEFAULT 0
);

-- Orders Table
CREATE TABLE orders (
    id BIGINT PRIMARY KEY,
    description TEXT,
    status VARCHAR(50),
    assigned_agent_id BIGINT REFERENCES agents(id)
);

-- Reassignment Suggestions Table
CREATE TABLE reassignment_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    recommended_agent_id BIGINT NOT NULL REFERENCES agents(id),
    previous_agent_id BIGINT,
    confidence_score DECIMAL(3,2),
    reasoning TEXT,
    alternative_recommendations_json TEXT,
    status VARCHAR,
    trigger_reason VARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT DEFAULT 0
);
select * from agents;
select * from orders;
select * from reassignment_suggestions;