package com.backend.zycus.utility;

public final class GlobalConstants {
	
	public static final String geminiError="Warning: No response content generated by the model.";
	public static final String RULE_BASED="RULE_BASED";
	public static final String AI_BASED="AI_BASED";
}
